APP_URL=https://demo.guru99.com/V4
BROWSER_TYPE=CHROME
DEFAULT_IMPLICIT_WAIT=5
GURU99_BANK_MANAGER_HOME_PAGE_TITLE=Guru99 Bank Manager HomePage
GURU99_BANK_HOME_PAGE_TITLE=Guru99 Bank Home Page
WELCOME_MSG=Welcome To Manager's Page of Guru99 Bank
TESTDATA_FILE_LOCATION=/testdata/TestData.xlsx
TESTDATA_FILE_SHEET_NAME=testdata